version: '3'

services:
  myapp:
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${DOCKER_TAG}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./volumes/sqlite:/volumes/sqlite
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SQLITE_DB_PATH=/volumes/sqlite/troskove.db
      - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN}
      - TEMPLATE_FOLDER_PATH=/troskove/templates
      - ALLOWED_TELEGRAM_USER_IDS=${ALLOWED_TELEGRAM_USER_IDS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
